# dcam_props.py
"""
Subset of DCAM property IDs and mode values for:
- opening camera / live streaming (trigger, timing)
- saving frames (image / buffer sizes, pixel type)
- exposure control
- binning and subarray (ROI)

Values copied from dcamprop.h (Apr 14, 2025).
"""

# ---------------------------------------------------------------------------
# Property IDs (DCAMIDPROP)
# ---------------------------------------------------------------------------

# --- TIMING / TRIGGER (for live streaming / trigger setup) ---

DCAM_IDPROP_TRIGGERSOURCE          = 0x00100110  # "TRIGGER SOURCE"
DCAM_IDPROP_TRIGGERACTIVE          = 0x00100120  # "TRIGGER ACTIVE"
DCAM_IDPROP_TRIGGER_MODE           = 0x00100210  # "TRIGGER MODE"
DCAM_IDPROP_TRIGGERPOLARITY        = 0x00100220  # "TRIGGER POLARITY"

DCAM_IDPROP_INTERNALFRAMERATE      = 0x00403810  # "INTERNAL FRAME RATE" (1/sec)
DCAM_IDPROP_INTERNAL_FRAMEINTERVAL = 0x00403820  # "INTERNAL FRAME INTERVAL" (sec)

# --- EXPOSURE ---

DCAM_IDPROP_EXPOSURETIME           = 0x001F0110  # "EXPOSURE TIME" (sec)
DCAM_IDPROP_EXPOSURETIME_CONTROL   = 0x001F0130  # "EXPOSURE TIME CONTROL"
DCAM_IDPROP_TRIGGER_FIRSTEXPOSURE  = 0x001F0200  # "TRIGGER FIRST EXPOSURE"
DCAM_IDPROP_TRIGGER_GLOBALEXPOSURE = 0x001F0300  # "TRIGGER GLOBAL EXPOSURE"

# --- ROI / BINNING / SUBARRAY ---

DCAM_IDPROP_BINNING                = 0x00401110  # "BINNING" (mode)
DCAM_IDPROP_BINNING_INDEPENDENT    = 0x00401120  # "BINNING INDEPENDENT"
DCAM_IDPROP_BINNING_HORZ           = 0x00401130  # "BINNING HORZ"
DCAM_IDPROP_BINNING_VERT           = 0x00401140  # "BINNING VERT"

DCAM_IDPROP_SUBARRAYHPOS           = 0x00402110  # "SUBARRAY HPOS"
DCAM_IDPROP_SUBARRAYHSIZE          = 0x00402120  # "SUBARRAY HSIZE"
DCAM_IDPROP_SUBARRAYVPOS           = 0x00402130  # "SUBARRAY VPOS"
DCAM_IDPROP_SUBARRAYVSIZE          = 0x00402140  # "SUBARRAY VSIZE"
DCAM_IDPROP_SUBARRAYMODE           = 0x00402150  # "SUBARRAY MODE"

DCAM_IDPROP_DIGITALBINNING_METHOD  = 0x00402160  # "DIGITALBINNING METHOD"
DCAM_IDPROP_DIGITALBINNING_HORZ    = 0x00402170  # "DIGITALBINNING HORZ"
DCAM_IDPROP_DIGITALBINNING_VERT    = 0x00402180  # "DIGITALBINNING VERT"

# --- IMAGE / BUFFER (for saving frames correctly) ---

DCAM_IDPROP_IMAGE_WIDTH            = 0x00420210  # "IMAGE WIDTH"
DCAM_IDPROP_IMAGE_HEIGHT           = 0x00420220  # "IMAGE HEIGHT"
DCAM_IDPROP_IMAGE_ROWBYTES         = 0x00420230  # "IMAGE ROWBYTES"
DCAM_IDPROP_IMAGE_FRAMEBYTES       = 0x00420240  # "IMAGE FRAMEBYTES"
DCAM_IDPROP_IMAGE_TOPOFFSETBYTES   = 0x00420250  # "IMAGE TOP OFFSET BYTES"
DCAM_IDPROP_IMAGE_PIXELTYPE        = 0x00420270  # "IMAGE PIXEL TYPE"
DCAM_IDPROP_IMAGE_CAMERASTAMP      = 0x00420300  # "IMAGE CAMERA STAMP"

DCAM_IDPROP_BUFFER_ROWBYTES        = 0x00420330  # "BUFFER ROWBYTES"
DCAM_IDPROP_BUFFER_FRAMEBYTES      = 0x00420340  # "BUFFER FRAME BYTES"
DCAM_IDPROP_BUFFER_TOPOFFSETBYTES  = 0x00420350  # "BUFFER TOP OFFSET BYTES"
DCAM_IDPROP_BUFFER_PIXELTYPE       = 0x00420360  # "BUFFER PIXEL TYPE"

# Optional but handy if you use frame bundle mode:
DCAM_IDPROP_FRAMEBUNDLE_MODE       = 0x00421010  # "FRAMEBUNDLE MODE"
DCAM_IDPROP_FRAMEBUNDLE_NUMBER     = 0x00421020  # "FRAMEBUNDLE NUMBER"
DCAM_IDPROP_FRAMEBUNDLE_ROWBYTES   = 0x00421030  # "FRAMEBUNDLE ROWBYTES"
DCAM_IDPROP_FRAMEBUNDLE_FRAMESTEPBYTES = 0x00421040  # "FRAMEBUNDLE FRAME STEP BYTES"


# ---------------------------------------------------------------------------
# Mode values (DCAMPROPMODEVALUE)
# ---------------------------------------------------------------------------

# --- General ON/OFF ---

DCAMPROP_MODE__OFF = 1  # "OFF"
DCAMPROP_MODE__ON  = 2  # "ON"

# --- Trigger source ---

DCAMPROP_TRIGGERSOURCE__INTERNAL   = 1  # "INTERNAL"
DCAMPROP_TRIGGERSOURCE__EXTERNAL   = 2  # "EXTERNAL"
DCAMPROP_TRIGGERSOURCE__SOFTWARE   = 3  # "SOFTWARE"
DCAMPROP_TRIGGERSOURCE__MASTERPULSE = 4 # "MASTER PULSE"

# --- Trigger active ---

DCAMPROP_TRIGGERACTIVE__EDGE       = 1  # "EDGE"
DCAMPROP_TRIGGERACTIVE__LEVEL      = 2  # "LEVEL"
DCAMPROP_TRIGGERACTIVE__SYNCREADOUT = 3  # "SYNCREADOUT"
DCAMPROP_TRIGGERACTIVE__POINT      = 4  # "POINT"

# --- Trigger mode ---

DCAMPROP_TRIGGER_MODE__NORMAL      = 1  # "NORMAL"
DCAMPROP_TRIGGER_MODE__PIV         = 3  # "PIV"
DCAMPROP_TRIGGER_MODE__START       = 6  # "START"
# (MULTIGATE / MULTIFRAME exist but are typically reserved / special)

# --- Trigger polarity ---

DCAMPROP_TRIGGERPOLARITY__NEGATIVE = 1  # "NEGATIVE"
DCAMPROP_TRIGGERPOLARITY__POSITIVE = 2  # "POSITIVE"

# --- Exposure control ---

DCAMPROP_EXPOSURETIME_CONTROL__OFF    = 1  # "OFF"
DCAMPROP_EXPOSURETIME_CONTROL__NORMAL = 2  # "NORMAL"

DCAMPROP_TRIGGER_FIRSTEXPOSURE__NEW     = 1  # "NEW"
DCAMPROP_TRIGGER_FIRSTEXPOSURE__CURRENT = 2  # "CURRENT"

# --- Binning (sensor / hardware binning) ---

DCAMPROP_BINNING__1   = 1    # "1X1"
DCAMPROP_BINNING__2   = 2    # "2X2"
DCAMPROP_BINNING__4   = 4    # "4X4"
DCAMPROP_BINNING__8   = 8    # "8X8"
DCAMPROP_BINNING__16  = 16   # "16X16"
DCAMPROP_BINNING__1_2 = 102  # "1X2"
DCAMPROP_BINNING__2_4 = 204  # "2X4"

# --- Digital binning method ---

DCAMPROP_DIGITALBINNING_METHOD__MINIMUM = 1  # "MINIMUM"
DCAMPROP_DIGITALBINNING_METHOD__MAXIMUM = 2  # "MAXIMUM"
DCAMPROP_DIGITALBINNING_METHOD__ODD     = 3  # "ODD"
DCAMPROP_DIGITALBINNING_METHOD__EVEN    = 4  # "EVEN"
DCAMPROP_DIGITALBINNING_METHOD__SUM     = 5  # "SUM"
DCAMPROP_DIGITALBINNING_METHOD__AVERAGE = 6  # "AVERAGE"
